substitutions:
  device_name: esp-termo
  project_version: "1.0.5"
  device_description: "Обеспечивает работу устройств в котельной"
dashboard_import:
  package_import_url: github://darkness0808/esp-termo/esp-termo.yaml@main
esphome:
  name: '${device_name}'
  comment: '${device_description}'
  friendly_name: 'ESP boilerhouse'
  project:
    name: "darkness0808.esp-termo"
    version: "${project_version}"
  on_loop:
    then:
      - if:
          condition:
            and:
              - lambda: 'return {id(water_press).state < id(min_press).state};'
              - binary_sensor.is_off: power
          then:
            - switch.turn_on: waterpump
            - lambda: 'id(power).publish_state(true);'
          else:
            - while:
                condition:
                  and:
                    - lambda: 'return {id(water_press).state > id(max_press).state};'
                    - binary_sensor.is_on: power
                then:
                  - switch.turn_off: waterpump
                  - lambda: 'id(power).publish_state(false);'

# Choose the right Platform
# esp32: https://esphome.io/components/esp32.html
# esp8266: https://esphome.io/components/esp8266.html
esp32:
  board: esp32dev
  framework:
    type: arduino
# Enable Web server
web_server:
  port: 80
# Enable logging
logger:
# Enable Home Assistant API
api:
  encryption:
    key: "aNDUbCO2byAMFXZdMu+p2T7SnD6nB1ZilduqKpWcuAg="
# Enable OTA update
ota:
  password: "7a47143c1f01cf53a5f8ca7119bf587d"
# Enable WIFI
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Termo Fallback Hotspot"
    password: "DNIc0lrbRK7w"
captive_portal:
binary_sensor:
  - platform: template
    device_class: power
    id: power
    internal: True
number:
  - platform: template
    name: "4_Water pressure max"
    id: max_press
    mode: box
    unit_of_measurement: "bar"
    optimistic: true
    min_value: 1
    max_value: 10
    step: 0.1
    restore_value: yes
    initial_value: 4.5
  - platform: template
    name: "5_Water pressure min"
    id: min_press
    mode: box
    unit_of_measurement: "bar"
    optimistic: true
    min_value: 1
    max_value: 10
    step: 0.1
    restore_value: yes
    initial_value: 3.5
switch:
  - platform: gpio
    pin: 13
    name: "7_Relay"
    id: waterpump
button:
  - platform: restart
    name: "8_Restart - ESP"
dallas:
  - pin: GPIO15
sensor:
  - platform: dallas
    address: 0x083c01d075ff8428
    name: "1_Temperature sensor 1"
  - platform: dallas
    address: 0xff031097794b6428
    name: "2_Temperature sensor 2"
  - platform: dallas
    address: 0xfd3c01d607752c28
    name: "3_Temperature sensor 3"
  - platform: adc
    id: water_press
    pin: 34
    update_interval: 500ms
    attenuation: auto
    name: "6_Water pressure"
    unit_of_measurement: "bar"
    accuracy_decimals: 4
    filters:
      - calibrate_linear:
          - 0.35 -> 0.0
          - 3.03 -> 10.0
      - sliding_window_moving_average:
          window_size: 10
          send_every: 1
